version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000" 
    environment:
      - MONGODB_URI=mongodb+srv://niarisiham:niari@cluster0.eevqfac.mongodb.net/CoffeData?retryWrites=true&w=majority
    volumes:
      - .:/app
    command: npm start
